from gpiozero import Motor
from time import sleep

motor1 = Motor(23, 24)
print("Motor 1 forward")
motor1.forward()
sleep(2)  
print("Motor 1 backward")
motor1.backward()
sleep(2)  
print("Motor 1 forward slow")
motor1.forward(0.20)
sleep(2)  
print("Motor 1 backward slow")
motor1.backward(0.20)
sleep(2)  
print("Motor 1 stop")
motor1.stop()

motor2 = Motor(20,21)
print("Motor 2 forward")
motor2.forward()
sleep(2)  
print("Motor 2 backward")
motor2.backward()
sleep(2)  
print("Motor 2 forward slow")
motor2.forward(0.20)
sleep(2)  
print("Motor 2 backward slow")
motor2.backward(0.20)
sleep(2)  
print("Motor 2 stop")
motor2.stop()